### ISSUE TITLE
Sharing to Facebook causes List Layouts for Trello to crash

### ISSUE THREAD

**Issue by dkistner1111** [natalieperna/layout-trello#14] opened 2015-11-24 13:17 UTC
Every time I share a page from, e.g., The Washington Post or elsewhere to Facebook via the site's share button, I get a popup saying List Layouts for Trello has crashed, click to reload. Just letting you know.

**Comment by natalieperna** [comment] 2015-12-21 17:13
I can't seem to reproduce this. On The Washington Post, for example, do you click the Facebook icon in the floating bar at the top of the page?

A crash log might help me debug it. I think you can log the error by:
1. Open Settings in Chrome.
2. Search for "crash".
3. Check off "Automatically send usage statistics and crash reports..." if it is not already selected.
4. When the extension crashes go to: [chrome://crashes/](chrome://crashes/) to find the crash report.

**Comment by dkistner1111** [comment] 2015-12-21 19:26
Trying again with just one...last time it bounced due to file size limit
exceeded.

**Comment by natalieperna** [comment] 2016-01-11 15:27
Closing as I cannot reproduce, feel free to reopen later if you can post more information.

**Closed by natalieperna** 2016-01-11 15:27 UTC

**Comment by dkistner1111** [comment] 2016-01-11 15:40
Thank you for trying. I still have the problem but I just reload.
